function createComponent(obj)

    %%% create
    obj.uifig  = uifigure('Name','Figure Capture','Position',[500,500,215,200]);
    obj.uigrid = uigridlayout(obj.uifig,[4 3]);

    [path,~,~] = fileparts( mfilename("fullpath") );
    obj.uiCapture = uibutton(obj.uigrid, ...
                      'Text'    ,'capture',...
                      'FontSize',18,...
                      'Icon'    ,fullfile(path,'image','camera.png'),...
                      'IconAlignment','top',...
                      'BackgroundColor',[0.8,0.8,0.8],...
                      "ButtonPushedFcn", @(src,event) obj.capture(obj.uiFileName.Value)...
                       );
    
    obj.uiFolderIcon  = uibutton(obj.uigrid, ...
                      'Text','',...
                      'Icon'    ,fullfile(path,'image','folder.png'),...
                      'IconAlignment','center',...
                      'BackgroundColor',[0.9,0.9,0.9],...
                      "ButtonPushedFcn", @(src,event) obj.setPath...
                       );
    
    obj.uiExtensionIcon = uibutton(obj.uigrid, ...
                      'Text','',...
                      'Icon'    ,fullfile(path,'image','setting.png'),...
                      'IconAlignment','center',...
                      'BackgroundColor',[0.9,0.9,0.9],...
                      "ButtonPushedFcn", @(src,event) obj.setExtension([],obj)...
                       );

    obj.uiFileName     = uitextarea(obj.uigrid);
    obj.uiTextFolder   = uilabel(obj.uigrid,'FontSize',8);
    obj.uiTextExtension= uilabel(obj.uigrid,'FontSize',8);
    
    obj.uiFileName.Value = ['Fig',char(datetime("now","Format","yyMMddHHmmss"))];

    tag_file = uilabel(obj.uigrid,'Text','Name','FontSize',6);
    tag_dir  = uilabel(obj.uigrid,'Text','Path','FontSize',6);
    tag_ext  = uilabel(obj.uigrid,'Text','Ext' ,'FontSize',6);

    %%%% UI LAYOUT
    obj.uigrid.RowHeight   = {80,'1x','1x','1x'};
    obj.uigrid.ColumnWidth = {28,'1x',20};

                                 % Caputure Botton
                                 obj.uiCapture.Layout.Row      = 1;
                                 obj.uiCapture.Layout.Column   = [1,3];

    % Tag "Name"                 % textarea >> file name
    tag_file.Layout.Row   = 2;   obj.uiFileName.Layout.Row     = 2;
    tag_file.Layout.Column= 1;   obj.uiFileName.Layout.Column  = 2;

    % Tag "Path"                 % textarea >> save path                % Folder Icon
    tag_dir.Layout.Row    = 3;   obj.uiTextFolder.Layout.Row   = 3;     obj.uiFolderIcon.Layout.Row   = 3;
    tag_dir.Layout.Column = 1;   obj.uiTextFolder.Layout.Column= 2;     obj.uiFolderIcon.Layout.Column= 3;

    % Tag ".ext"                 % choice >> extension
    tag_ext.Layout.Row    = 4;   obj.uiTextExtension.Layout.Row   = 4;  obj.uiExtensionIcon.Layout.Row   = 4;
    tag_ext.Layout.Column = 1;   obj.uiTextExtension.Layout.Column= 2;  obj.uiExtensionIcon.Layout.Column= 3;
end
